/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.guava:guava:29.0-jre")
    implementation("commons-io:commons-io:2.7")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("org.apache.commons:commons-lang3:3.10")
    implementation("org.apache.commons:commons-text:1.9")
    implementation("commons-beanutils:commons-beanutils:1.9.4")
    implementation("org.apache.httpcomponents:httpclient:4.5.12")
    implementation("org.apache.httpcomponents:httpmime:4.5.12")
    implementation("org.eclipse.jetty.websocket:websocket-client:9.4.35.v20201120")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.0")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.0.2")
    testImplementation("org.assertj:assertj-core:3.16.1")
    testImplementation("org.mockito:mockito-core:2.28.2")
    testImplementation("org.bouncycastle:bcpkix-jdk15on:1.65")
}

group = "net.ravendb"
version = "5.2.1-SNAPSHOT"
description = "RavenDB Java Client"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
